import { Component, signal } from '@angular/core';
import { Productitem } from '../productitem/productitem';
import { Product } from '../../models/product';

@Component({
  selector: 'app-productlist',
  standalone: true,
  imports: [Productitem],
  templateUrl: './productlist.html',
  styleUrls: ['./productlist.css'],
})
export class Productlist {
  protected readonly products = signal<Product[]>([
    {
      id: 1,
      name: 'Baskets blanches Guess',
      description: 'Sneakers blanches en cuir, détails monogramme',
      soldPrice: 25000,
      regularPrice: 32000,
      imageUrl: 'assets/images/Products/10138675087.jfif',
      createdAt: new Date('2026-01-08'),
      categories: ['chaussure', 'homme', 'baskets'],
    },
    {
      id: 2,
      name: 'Mocassins en daim Hermès',
      description: 'Mocassins marron en daim, boucle métallique',
      soldPrice: 35000,
      regularPrice: 42000,
      imageUrl: 'assets/images/Products/10149427496.jfif',
      createdAt: new Date('2026-01-14'),
      categories: ['chaussure', 'homme', 'cuir'],
    },
    {
      id: 3,
      name: 'Survêtement Joma',
      description: 'Ensemble jogging orange et noir, coupe sport',
      soldPrice: 20000,
      regularPrice: 25000,
      imageUrl: 'assets/images/Products/103564.881_1.jpg',
      createdAt: new Date('2026-01-20'),
      categories: ['vêtement', 'homme', 'sport'],
    },
    {
      id: 4,
      name: 'Survêtement Kappa',
      description: 'Ensemble jogging noir et écru, logo brodé',
      soldPrice: 22000,
      regularPrice: 28000,
      imageUrl: 'assets/images/Products/331R2JW_A09_1.webp',
      createdAt: new Date('2026-01-27'),
      categories: ['vêtement', 'homme', 'sport'],
    },
    {
      id: 5,
      name: 'Ensemble Dashiki bleu et or',
      description: 'Tunique et pantalon à motifs dorés traditionnels',
      soldPrice: 28000,
      regularPrice: 35000,
      imageUrl: 'assets/images/Products/71Pv5qp5KFL._AC_UY1000_.jpg',
      createdAt: new Date('2026-02-03'),
      categories: ['vêtement', 'homme', 'traditionnel'],
    },
    {
      id: 6,
      name: 'Chemise slim bleu marine',
      description: 'Chemise homme unie, manches longues, coupe ajustée',
      soldPrice: 12000,
      regularPrice: 15000,
      imageUrl: 'assets/images/Products/chemise-hommes-uni-en-slim-a-manches-longues-coupe.webp',
      createdAt: new Date('2026-02-10'),
      categories: ['vêtement', 'homme', 'chemise'],
    },
    {
      id: 7,
      name: 'Baskets à strass',
      description: 'Sneakers bleu et vert ornées de strass',
      soldPrice: 30000,
      regularPrice: 38000,
      imageUrl: 'assets/images/Products/dfe55277-28f5-4fcb-a2e8-729b258c91da.jpg',
      createdAt: new Date('2026-02-17'),
      categories: ['chaussure', 'femme', 'baskets'],
    },
    {
      id: 8,
      name: 'Tunique Dashiki bleue',
      description: 'Tunique longue à broderies dorées, style africain',
      soldPrice: 18000,
      regularPrice: 23000,
      imageUrl: 'assets/images/Products/images (1).jfif',
      createdAt: new Date('2026-02-24'),
      categories: ['vêtement', 'homme', 'traditionnel'],
    },
    {
      id: 9,
      name: 'Robe cardigan blanche',
      description: 'Robe cardigan blanc et noir à boutons dorés',
      soldPrice: 24000,
      regularPrice: 30000,
      imageUrl: 'assets/images/Products/images (2).jfif',
      createdAt: new Date('2026-03-02'),
      categories: ['vêtement', 'femme', 'chic'],
    },
    {
      id: 10,
      name: 'Robe en broderie anglaise',
      description: "Robe d'été blanche courte, broderie anglaise",
      soldPrice: 20000,
      regularPrice: 26000,
      imageUrl: 'assets/images/Products/images (3).jfif',
      createdAt: new Date('2026-03-09'),
      categories: ['vêtement', 'femme', 'été'],
    },
    {
      id: 11,
      name: 'Robe longue blanche boutonnée',
      description: 'Robe longue blanche en coton, boutons devant',
      soldPrice: 22000,
      regularPrice: 27000,
      imageUrl: 'assets/images/Products/images (4).jfif',
      createdAt: new Date('2026-03-16'),
      categories: ['vêtement', 'femme', 'été'],
    },
    {
      id: 12,
      name: 'Robe noire dos-nu',
      description: 'Robe noire moulante à dos nu, col licou',
      soldPrice: 17000,
      regularPrice: 21000,
      imageUrl: 'assets/images/Products/images (5).jfif',
      createdAt: new Date('2026-03-23'),
      categories: ['vêtement', 'femme', 'soirée'],
    },
    {
      id: 13,
      name: 'Chaussures Richelieu en cuir',
      description: 'Richelieu marron en cuir, finition perforée',
      soldPrice: 30000,
      regularPrice: 36000,
      imageUrl: 'assets/images/Products/images (6).jfif',
      createdAt: new Date('2026-03-30'),
      categories: ['chaussure', 'homme', 'cuir'],
    },
    {
      id: 14,
      name: 'Baskets denim Louis Vuitton',
      description: 'Sneakers bleu denim et blanc, semelle épaisse',
      soldPrice: 32000,
      regularPrice: 40000,
      imageUrl: 'assets/images/Products/images (7).jfif',
      createdAt: new Date('2026-04-06'),
      categories: ['chaussure', 'homme', 'baskets'],
    },
    {
      id: 15,
      name: 'Baskets casual bleu et marron',
      description: 'Baskets de ville bleu marine et marron, confortables',
      soldPrice: 19000,
      regularPrice: 24000,
      imageUrl: 'assets/images/Products/images (8).jfif',
      createdAt: new Date('2026-04-13'),
      categories: ['chaussure', 'homme', 'baskets'],
    },
    {
      id: 16,
      name: 'Escarpins dorés à paillettes',
      description: 'Escarpins à talon haut, paillettes dorées',
      soldPrice: 23000,
      regularPrice: 28000,
      imageUrl: 'assets/images/Products/images (9).jfif',
      createdAt: new Date('2026-04-20'),
      categories: ['chaussure', 'femme', 'soirée'],
    },
    {
      id: 17,
      name: 'Costume croisé bleu marine',
      description: 'Costume homme croisé bleu marine, boutons dorés',
      soldPrice: 45000,
      regularPrice: 55000,
      imageUrl: 'assets/images/Products/images.jfif',
      createdAt: new Date('2026-04-27'),
      categories: ['vêtement', 'homme', 'cérémonie'],
    },
    {
      id: 18,
      name: 'Chemise habillée col blanc',
      description: 'Chemise bleu marine à col et poignets blancs',
      soldPrice: 14000,
      regularPrice: 18000,
      imageUrl: 'assets/images/Products/it2832-1.png',
      createdAt: new Date('2026-05-04'),
      categories: ['vêtement', 'homme', 'chemise'],
    },
    {
      id: 19,
      name: 'Chemise à carreaux bleue',
      description: 'Chemise homme à carreaux bleus, manches longues',
      soldPrice: 13000,
      regularPrice: 16000,
      imageUrl: 'assets/images/Products/it786-3.png',
      createdAt: new Date('2026-05-11'),
      categories: ['vêtement', 'homme', 'chemise'],
    },
    {
      id: 20,
      name: 'Robe fourreau bordeaux',
      description: 'Robe fourreau en velours bordeaux à sequins',
      soldPrice: 26000,
      regularPrice: 33000,
      imageUrl: 'assets/images/Products/product-1.jpg',
      createdAt: new Date('2026-05-18'),
      categories: ['vêtement', 'femme', 'soirée'],
    },
    {
      id: 21,
      name: 'Robe de soirée bordeaux à sequins',
      description: 'Robe longue bordeaux, manches à sequins',
      soldPrice: 27000,
      regularPrice: 34000,
      imageUrl: 'assets/images/Products/product-2.jpeg',
      createdAt: new Date('2026-05-25'),
      categories: ['vêtement', 'femme', 'soirée'],
    },
    {
      id: 22,
      name: 'Escarpins beige doré',
      description: 'Escarpins beige à pointe pailletée dorée',
      soldPrice: 24000,
      regularPrice: 30000,
      imageUrl: 'assets/images/Products/shooz-de-luxe-780x450.jpg',
      createdAt: new Date('2026-06-01'),
      categories: ['chaussure', 'femme', 'soirée'],
    },
    {
      id: 23,
      name: 'Blazer rose à manches cape',
      description: 'Veste blazer rose à manches cape, ceinture à boucle',
      soldPrice: 25000,
      regularPrice: 31000,
      imageUrl: 'assets/images/Products/veste-a-manches-cape-avec-ceinture.jpg',
      createdAt: new Date('2026-06-08'),
      categories: ['vêtement', 'femme', 'chic'],
    },
  ]);
}
